name: Update Dependency Tree

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  publish:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout from Github ü•ö
        uses: actions/checkout@v3
      - name: Set up JDK 17 üê£
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Set up Maven 3.9.6 üê§
        uses: stCarolas/setup-maven@v.4.5
        with:
          maven-version: 3.9.6 # default is 3.8.2
      - name: Debug üêõ
        run: mvn -version && chmod +x mvnw
      - name: Maven Dependency Tree Dependency Submission
        # You may pin to the exact commit or the version.
        # uses: advanced-security/maven-dependency-submission-action@fcd7eab6b6d22946badc98d1e62665cdee93e0ae
        uses: advanced-security/maven-dependency-submission-action@v3.0.3
        #with:
          # The directory that contains the maven project
          #directory: ${{ github.workspace }} # optional, default is ${{ github.workspace }}
          # Optional path to a Maven settings.xml file for the dependencies to be resolved
          #settings-file: # optional
          # Flag for optionally ignoring any maven wrapper files (mvnw) and instead rely on the PATH provided mvn
          #ignore-maven-wrapper: # optional
          # Additional maven arguments to add to the command line invocation of maven when it generates the dependency snapshot
          #maven-args: # optional, default is 
          # Optionally include the file name in the dependency snapshot report to GitHub. This is required to be true if you want the results in the dependency tree to have a working link.
          #snapshot-include-file-name: # optional, default is true
          # An optional override to specify the path to the file in the repository that the snapshot should be associated with.
          #snapshot-dependency-file-name: # optional
          # The GitHub token to use to submit the depedency snapshot to the repository
          #token: ${{ github.token }} # optional, default is ${{ github.token }}
          
